############## Spring #####################
spring:
  main:
    allow-circular-references: true  #允许循环引用
  datasource:
    hikari:
      max-lifetime: 120000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:21001/rabbitbot?characterEncoding=utf-8
    username: root
    password:
server:
  port: 31210

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.mikulink.rabbitbot.entity.db
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

############## RabbitBot #####################
#名称 如果遇到乱码可尝试转为Unicode
bot:
  name:
    cn: 兔叽
    #名称 英文
    en: RabbitBot
  #兔叽版本
  version: AI_NT_0.3
  #配置admin权限的qq号,多个以,隔开 用于远程进行敏感操作
  master: 114514
  #登录协议 ANDROID_PHONE / ANDROID_PAD / ANDROID_WATCH / IPAD / MACOS
  protocol: ANDROID_WATCH
  #是否二维码登录
  isQrLogin: true
  #NapCat
  napcat:
    apiurl: http://localhost:31011

############# 文件相关 ######################
#在 每个文件一个路径配置 和 仅主目录写为配置 两个方案中难舍 但眼下两种方案效果实为无异
#啊。。随便了=A=

#配置文件路径
file:
  path:
    config: config
    #资源文件路径
    data: data

############# AI ######################
deepseek:
  token: sk-test

############# 代理相关 ######################
#地址
proxy:
  address: 127.0.0.1
  #端口
  prot: 31051

############## Pixiv #####################
#pixiv 曲奇(
pixiv:
  cookie: pixivCookie

############## Saucenao #####################
#Saucenao api的key
saucenao:
  key: saucenaoKey

############## 高德地图 #####################
#高德api的key
amap:
  key: 高德key

############## 新浪微博 #####################
#新浪微博api的token
weibo:
  token: test

############## BiliBili #####################
#b站的cookie
bilibili:
  cookie:cookie

############## 网易云音乐自建api #####################
#自建的api链接
#参照文档 https://github.com/Binaryify/NeteaseCloudMusicApi
neteasecloud:
  apiurl: http://localhost:3000

############## 涩图 #####################
#每个人的色图请求间隔
setu:
  split:
    time: 60000
#MirlKoi 请求地址
mirlkoi:
  setu:
    url: https://setu
